# Generated by Selenium IDE

import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

class TestTestseleniumpy():
    def setup_method(self, method):
        # Configura ChromeDriver automáticamente usando webdriver_manager
        chrome_service = Service(ChromeDriverManager().install())
        self.driver = webdriver.Chrome(service=chrome_service)
        self.driver.maximize_window()
        self.vars = {}
  
    def teardown_method(self, method):
        # Cierra el navegador después de cada prueba
        self.driver.quit()
  
    def test_testseleniumpy(self):
        # Navega a la página de inicio
        self.driver.get("http://127.0.0.1:5000/")
        
        # Interactúa con los elementos de la página
        self.driver.find_element(By.CSS_SELECTOR, ".nav-link:nth-child(1)").click()
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("user1@example.com")
        self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(3) > .col-md-6").click()
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("1234")
        self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
        
        # Verifica el acceso al perfil
        self.driver.find_element(By.CSS_SELECTOR, ".text-dark").click()
        self.driver.find_element(By.LINK_TEXT, "My profile").click()
