services:
  web:
    container_name: web_app_container
    image: drorganvidez/uvlhub:dev
    env_file:
      - ../.env
    expose:
      - "5000"
    depends_on:
      - db
      - fakenodo
    environment:
      - FAKENODO_URL=http://fakenodo:5001
    build:
      context: ../
      dockerfile: docker/images/Dockerfile.dev
    volumes:
      - ../:/app
      - /var/run/docker.sock:/var/run/docker.sock
    command: [ "sh", "-c", "sh /app/docker/entrypoints/development_entrypoint.sh" ]
    networks:
      - uvlhub_network
    
  discordbot:
    container_name: discord_bot_container
    image: discordbot_container
    env_file:
      - ../.env 
    build:
      context: ../  
      dockerfile: docker/images/Dockerfile.discord
    depends_on:
      - db
      - web
    command: [ "sh", "/app/docker/entrypoints/discordbot_entrypoint.sh" ]
    networks:
      - uvlhub_network
  
  fakenodo:
    container_name: fakenodo
    image: fakenodo
    expose:
      - "5001"
    build:
      context: ../
      dockerfile: docker/images/Dockerfile.fakenodo
    volumes:
      - ../:/fakenodo
    ports:
      - "5001:5001"
    command: [ "python", "fakenodo/run.py" ]
    networks:
      - uvlhub_network

  db:
    container_name: mariadb_container
    env_file:
      - ../.env
    build:
      context: ../
      dockerfile: docker/images/Dockerfile.mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - uvlhub_network

  nginx:
    container_name: nginx_web_server_container
    image: nginx:latest
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - uvlhub_network

volumes:
  db_data:

networks:
  uvlhub_network:
