name: Deploy to Render

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

jobs:

  deploy:
    if: github.repository == 'salmorejo-hub/uvlhub' && (github.base_ref == 'main' || github.base_ref == '')
    name: Deploy to Render
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
